name: iOS Build & Logs

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build SwiftUI App (Simulator)
        run: |
          xcodebuild \
            -scheme PTTCallApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            clean build
